version: '3.7'
services:
 web:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/Django_Blog_magicauth
   ports:
     - 8888:8000
   env_file:
     - ./env/django.env
   depends_on:
     - postgres

 postgres:
   restart: always
   image: postgres:latest
   env_file:
     - ./env/postgresql.env
   volumes:
     - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: